Microverse Project : First Hello Microverse Project
PremChand12/hello-world-microverse pull request #1
Opened 2023-07-04 14:52 UTC by PremChand12

## First Microverse Project : -
     
      In this project : 
          -Added HTML and CSS files.
          -Added Linters 
          -Created New Branches

2023-07-04 15:19 UTC, usorfaitheloho requested changes
> Hi @PremChand12  ,
> 
> Good job so far! There are some issues that you still need to work on to go to the next project but you are almost there!

 ![](https://camo.githubusercontent.com/679757134a8fee76cfe1941f9f3ecb0e0cf56dd02da4498268ce31f0dacdfca3/68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f556461535559436c723932636a57706556782f67697068792e676966) [ ](https://camo.githubusercontent.com/679757134a8fee76cfe1941f9f3ecb0e0cf56dd02da4498268ce31f0dacdfca3/68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f556461535559436c723932636a57706556782f67697068792e676966)
> 
> ## Highlights
> * All linter checks passed ✔️
> * Descriptive pull request ✔️
> * Used GitHub flow ✔️
> 
> ## Required Changes ♻️
> _Check the comments under the review._
> 
> ## Optional suggestions
> _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
> 
> Cheers and Happy coding!👏👏👏
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
> 
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-04 15:19 UTC, usorfaitheloho commented on README.md
> +
Kindly remove all commented code from your README file to enable you have a clean code that is easily maintainable that is also easy to understand 😄

2023-07-04 15:19 UTC, usorfaitheloho commented on README.md
> + -->
Kindly remove all commented code from your README file to enable you have a clean code that is easily maintainable that is also easy to understand 😄

2023-07-04 15:19 UTC, usorfaitheloho commented on README.md
> +--->
Kindly remove all commented code from your README file to enable you have a clean code that is easily maintainable that is also easy to understand 😄

2023-07-04 15:19 UTC, usorfaitheloho commented on README.md
> +--->
Kindly remove all commented code from your README file to enable you have a clean code that is easily maintainable that is also easy to understand 😄

2023-07-04 15:19 UTC, usorfaitheloho commented on README.md
> +--->
Kindly remove all commented code from your README file to enable you have a clean code that is easily maintainable that is also easy to understand 😄

2023-07-04 15:19 UTC, usorfaitheloho commented on README.md
> +--->
Kindly remove all commented code from your README file to enable you have a clean code that is easily maintainable that is also easy to understand 😄

2023-07-04 15:19 UTC, usorfaitheloho commented on README.md
> + -->
Kindly remove all commented code from your README file to enable you have a clean code that is easily maintainable that is also easy to understand 😄

2023-07-04 15:19 UTC, usorfaitheloho commented on README.md
> +- [ ] **[new_feature_3]**
Please kindly add features that will be implemented in the future,so a user knows what to be expected in the future 😄

2023-07-04 15:19 UTC, usorfaitheloho commented on README.md
> +<!-- LICENSE -->
The FAQ is the only optional section of the README file so when you don't have anything to write there, please remove it 👍

2023-07-04 15:19 UTC, usorfaitheloho commented on README.md
> +This project is [MIT](./LICENSE) licensed.
Kindly add an MIT file and attach the link here as your link is broken here, so as to enable you have a clean code 👍

2023-07-04 18:45 UTC, brainconnect93 requested changes
## STATUS: Changes Required :recycle:

### Hi @PremChand12, 👋 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media.tenor.com/isiLRnxz3zwAAAAM/cat-driving-serious.gif" width="500px" height="300px">

### To Highlight :1st_place_medal: 

- Descriptive proper Pull Request summary. ✔️  
- Hello Microverse project done ✔️ 
- There is a `.gitignore` file listing `test.md` file and `node_modules` ✔️
- Good use of GitHub flow ✔️ 

### Changes Required

- [x]  _Please check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me on( @brainconnect93 ) in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-04 18:45 UTC, brainconnect93 commented on README.md
> +- License
- [ ] [Optional] Kindly remove this section as it is not needed in your readme file. You already have the table of content below.

2023-07-04 18:45 UTC, brainconnect93 commented on README.md
> +
- [ ] As suggested by the previous reviewer, Kindly add the MIT license link to your readme file as this serves as a copywrite that gives the visitor of your page access to make use of the content you have on your page.
Add the MIT file to your root directory and target it in your readme file

2023-07-05 00:34 UTC, bobb-Rob approved these changes
## STATUS: APPROVED ✔️ 🍾 🍾 🍾 🥳 🥳 🥳 

Hi @PremChand12, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![](https://camo.githubusercontent.com/2c67944c14f5c74b9b607df18d73efb0c423dd148b3e10cb75b445a00220332e/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f5061536e555a573145657970756c734f77642f67697068792e676966)

## Highlights
✅ No Linter error
✅ Correct use of GitHub flow
✅ Very descriptive Pull Request(PR)
✅ Neat Commit messages

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-05 01:28 UTC, PremChand12 commented
Thank you so much for the great news!

On Wed, Jul 5, 2023, 06:05 Robertson Arthur ***@***.***>
wrote:

> ***@***.**** approved this pull request.
> STATUS: APPROVED ✔️ 🍾 🍾 🍾 🥳 🥳 🥳
>
> Hi @PremChand12 <https://github.com/PremChand12>,
>
> Your project is complete! There is nothing else to say other than... it's
> time to merge it [image: :shipit:]
> Congratulations! 🎉
>
>
> <https://camo.githubusercontent.com/2c67944c14f5c74b9b607df18d73efb0c423dd148b3e10cb75b445a00220332e/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f5061536e555a573145657970756c734f77642f67697068792e676966>
> Highlights
>
> ✅ No Linter error
> ✅ Correct use of GitHub flow
> ✅ Very descriptive Pull Request(PR)
> ✅ Neat Commit messages
> Optional suggestions
>
> *Every comment with the [OPTIONAL] prefix won't stop the approval of this
> PR. However, I strongly recommend you to take them into account as they can
> make your code better. Some of them were simply missed by the previous
> reviewer and addressing them will really improve your application.*
>
> Cheers and Happy coding!👏👏👏
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
> Please, remember to tag me in your question so I can receive the
> notification.
> ------------------------------
>
> *As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a
> limited number of reviews per project (check the exact number in your
> Dashboard). If you think that the code review was not fair, you can request
> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/PremChand12/hello-world-microverse/pull/1#pullrequestreview-1513506921>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AZVPCOBMRNYBSKOGWBPEZWTXOSZDVANCNFSM6AAAAAAZ53EEJA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-07-05 01:53 UTC, merged